### PR TITLE
(fix) Revert SocialNetwork: add pipeline for redis cluster - fix Docker build

### PR DESCRIPTION
**Pull request by przmk0**

### CODE REVIEW

**Comment by przmk0** [comment]
@gavinlichn please take a look into your latest change, it breaks Docker build for social network

**Comment by gavinlichn** [comment]
Need to build the thrift-microservice-social-deps image first.  Added funcion "get_shards_pool" to the redis++ API and included to the deps image.

Please refer to socialNetwork/docker/thrift-microservice-deps/cpp/Dockerfile

**Comment by przmk0** [comment]
@gavinlichn - thanks for explanation!

Looks like public images were not updated for a long time:
image

@cdelimitrou - can we have them updated? Currently social network is not building without new deps image mentioned by @gavinlichn.

**Comment by przmk0** [comment]
@cdelimitrou - we can close this PR or merge it and re-apply @gavinlichn changes once deps image is updated.

**Comment by gavinlichn** [comment]
Hi, @cdelimitrou can you help to share the plan please?

Wil we update the  **yg397/thrift-microservice-social-deps**  deps image, and merge the patch again?
Or prefer to re-work the patch?

**Pull request merged**
