### PR TITLE
Redis pipeline enablement

### PR DESCRIPTION
**Pull request by gavinlichn**
Enabled Redis pipeline on cluster
And include redis-plus-plus change also, to avoid build dependency failure.

### CODE REVIEW

**Comment by gavinlichn** [comment]
This PR include the dependency change also. 
Will avoid build failure @przmk0

**Comment by msimonin** [comment]
Is there a chance to fix #182  at the same time ?

**Comment by gavinlichn** [comment]
> Is there a chance that it also fix #182 at the same time ?

This patch is non ralated to the issue.  My patch change the code only with redis cluster, will not impact legacy redis feature.

Acturally I have verified docker-compose(single machine), but cannot reproduce issue #182 at all.

**Comment by gavinlichn** [comment]
@cdelimitrou can you help to review and merge this pach please?
The issue #182 has been resolved. And not ralated to this PR.

**Pull request merged**
