### PR TITLE
Hotel reservation support for kubernetes 

### LINKED ISSUE #69: Where are the .yaml files for kubernetes deployment?
Hello,

Why have the .yaml files for k8s deployment been removed from the master branch?
Aren't they correctly working now?

Thanks in advance!

### PR DESCRIPTION
**Pull request by salehsedghpour**
As there is a need for supporting Kubernetes. I've made some changes to use the DNS in Kubernetes. Also I added deployments for kubernetes and a build script for docker images. Currently all deployments are using my personal repository. 
Maybe it can close #69 .

### CODE REVIEW

**Comment by zarak-shahjee** [comment]
https://github.com/delimitrou/DeathStarBench/issues/69#issuecomment-734474007

The issue mentioned in the above link is being encountered by me for social network .
Is there anyway we can use kubernetes for social network ?

**Comment by zarak-shahjee** [comment]
https://github.com/delimitrou/DeathStarBench/issues/69#issuecomment-734474007

The issue mentioned in the above link is being encountered by me for social network .
Is there anyway we can use kubernetes for social network ?

**Comment by salehsedghpour** [comment]
I'm not sure about this. But I guess you can use the helm chart in social network for deploying on kubernetes. 
checkout [here](../tree/master/socialNetwork/helm-chart)

**Comment by salehsedghpour** [comment]
I'm not really sure about the recent updates. You can open an issue or ask about it using the email provided in the readme. Also, I found this old version which has the support for k8s. https://github.com/delimitrou/DeathStarBench/tree/6970bda1235bcc74ee798d1e8fef97bab6c902a2/socialNetwork

**Comment by zarak-shahjee** [comment]
Can you please explain this part of  README given for older version

" Set the resolver to be the FQDN of the core-dns or kube-dns service of your cluster in <path-of-repo>/socialNetwork/nginx-web-server/conf/nginx-k8s.conf and <path-of-repo>/socialNetwork/media-frontend/conf/nginx-k8s.conf  "

**Comment by salehsedghpour** [comment]
If you look at the following line:

**Comment by zarak-shahjee** [comment]
I got rid of the above error by removing .conf extension in both nginx-thrift and media-frontend file.

Now theses pods are running but still i have the same issue that i had with the new-version of Deathstarbench that is:
when i try 
`$ minikube -n social-network service --all`

and see the URL of nginx-thrift ,media-frontend and jaegar-out

The URL for jaegar-out **works properly** and opens ups the jaeger UI
but when i try going to URL of nginx-thrift or media-frontend they show :

`192.168.49.2 refused to connect.`

Please help.

**Comment by salehsedghpour** [comment]
I'm not sure about the error you are getting. I guess you should discuss it with the main contributors

**Comment by zarak-shahjee** [comment]
Thank you for your help though.

**Pull request merged**
