### PR TITLE
feature: pin binaries to create proto buffer go code

### LINKED ISSUE #302: How to regenerate .pb.go files for hotel reservation?
Hello, 

I am trying to rebuild the *.pb.go files for hotel reservation. 
I am using the command `make proto` to generate these files.
And I'm using the following versions:

- Go: 1.21.4
- lib-protoc: 3.19.4
- proto-gen-go-grpc: 1.3.0
- protobuf: 1.5.3

Then on running `docker-compose build`:
```
# github.com/delimitrou/DeathStarBench/hotelreservation/services/user/proto
services/user/proto/user.pb.go:25:17: undefined: proto.ProtoPackageIsVersion3
services/user/proto/user.pb.go:58:35: undefined: proto.InternalMessageInfo
services/user/proto/user.pb.go:104:34: undefined: proto.InternalMessageInfo
# github.com/delimitrou/DeathStarBench/hotelreservation/services/search/proto
services/search/proto/search.pb.go:25:17: undefined: proto.ProtoPackageIsVersion3
services/search/proto/search.pb.go:60:41: undefined: proto.InternalMessageInfo
services/search/proto/search.pb.go:120:40: undefined: proto.InternalMessageInfo
# github.com/delimitrou/DeathStarBench/hotelreservation/services/reservation/proto
services/reservation/proto/reservation.pb.go:25:17: undefined: proto.ProtoPackageIsVersion3
services/reservation/proto/reservation.pb.go:61:35: undefined: proto.InternalMessageInfo
services/reservation/proto/reservation.pb.go:128:34: undefined: proto.InternalMessageInfo
# github.com/delimitrou/DeathStarBench/hotelreservation/services/profile/proto
services/profile/proto/profile.pb.go:25:17: undefined: proto.ProtoPackageIsVersion3
services/profile/proto/profile.pb.go:58:35: undefined: proto.InternalMessageInfo
services/profile/proto/profile.pb.go:104:34: undefined: proto.InternalMessageInfo
services/profile/proto/profile.pb.go:148:33: undefined: proto.InternalMessageInfo
services/profile/proto/profile.pb.go:229:35: undefined: proto.InternalMessageInfo
services/profile/proto/profile.pb.go:318:33: undefined: proto.InternalMessageInfo
# github.com/delimitrou/DeathStarBench/hotelreservation/services/rate/proto
services/rate/proto/rate.pb.go:25:17: undefined: proto.ProtoPackageIsVersion3
services/rate/proto/rate.pb.go:59:35: undefined: proto.InternalMessageInfo
services/rate/proto/rate.pb.go:112:34: undefined: proto.InternalMessageInfo
services/rate/proto/rate.pb.go:155:36: undefined: proto.InternalMessageInfo
services/rate/proto/rate.pb.go:227:36: undefined: proto.InternalMessageInfo
# github.com/delimitrou/DeathStarBench/hotelreservation/services/geo/proto
services/geo/proto/geo.pb.go:25:17: undefined: proto.ProtoPackageIsVersion3
services/geo/proto/geo.pb.go:59:35: undefined: proto.InternalMessageInfo
services/geo/proto/geo.pb.go:105:34: undefined: proto.InternalMessageInfo
# github.com/delimitrou/DeathStarBench/hotelreservation/services/recommendation/proto
services/recommendation/proto/recommendation.pb.go:25:17: undefined: proto.ProtoPackageIsVersion3
services/recommendation/proto/recommendation.pb.go:60:35: undefined: proto.InternalMessageInfo
services/recommendation/proto/recommendation.pb.go:113:34: undefined: proto.InternalMessageInfo
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GO111MODULE=on go install -ldflags="-s -w" -mod=vendor ./cmd/...' returned a non-zero code: 1
```

Before PR #288 I was able to use the following  version to regenerate the .pb.go files:
- Go: 1.18
- lib-protoc: 3.19.4
- proto-gen-go-grpc: 1.3.0
- protobuf: 1.5.3
This version combination does not work after PR #288 
I upgraded the Go version since the Go version in Dockerfile was upgraded to 1.21 after PR #288 

Can you please let me know which versions to use to re-generate the .pb.go files?

### PR DESCRIPTION
**Pull request by Red-GV**
This PR completes #294 , which was reverted with #295 due to missing code. However, I would like to merge after #299 in order to ensure that the `go.mod` and `go.sum` files are properly cleaned. 

Fixes #302

### CODE REVIEW

**Comment by Red-GV** [comment]
Please note https://github.com/delimitrou/DeathStarBench/pull/303/commits/9f883c3a3499013032ad8281b58d0f5cffb70d4f which changes the consul resolver library. The incoming library is an MIT licensed software, so I don't think there should be any problems with the licensing.

**Comment by Red-GV** [comment]
Hello @cdelimitrou, I was just wondering about the status of this PR? Is there anything I need to in order to get this PR through?

**Comment by cdelimitrou** [comment]
Please resolve the conflicts above, and then we can accept the PR. Thanks.

**Comment by Red-GV** [comment]
Conflicts resolved. @cdelimitrou

**Pull request merged**
